CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    passwoed VARCHAR(256) NOT NULL,
    isAdmin BOOLEAN DEFAULT FALSE NOT NULL,
    isActive BOOLEAN NOT NULL
)